### ISSUE TITLE
Should text() be a second Observable?

### ISSUE THREAD

**Issue by paddlefish** [tangledfruit/rx-fetch#2]
Fetch supports handling output a variety of ways-- either as text(), as arrayBuffer() or blob() or json() or formData(). It looks to me as though fetch allows only ONE of those calls to complete (for whatever reason -- see implementation of consumed() in https://github.com/github/fetch/blob/master/fetch.js) and if you call more than one it generates an error.

Perhaps it's worthwhile following that pattern and add text(), arrayBuffer(), etc... calls that return Observables instead of baking in the text() into the initial result?

**Comment by tangledfruit** [comment]
Fixed by #3.
